---
fixtures:
  repositories:
    simplib:
      repo: "https://github.com/simp/pupmod-simp-simplib"
      branch: "master"
    stdlib:
      repo: "https://github.com/simp/puppetlabs-stdlib"
      branch: "master"
  symlinks:
    compliance_markup: "#{source_dir}"
